Enhance workflow with ignore_vermagic input
Added 'ignore_vermagic' input option to workflow dispatch.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,11 +3,17 @@ name: Build Custom OpenWrt
 on:
   workflow_dispatch:
     inputs:
-        force_build:
-          description: 'Force build'
-          required: false
-          default: false
-          type: boolean
+      force_build:
+        description: 'Force build'
+        required: false
+        default: false
+        type: boolean
+        
+      ignore_vermagic:
+        description: 'Ignore vermagic'
+        required: false
+        default: false
+        type: boolean
           
   schedule:
     - cron: '0 0 * * 0'     # Опционально: автоматическая сборка каждое воскресенье в 00:00
@@ -46,9 +52,34 @@ jobs:
           LATEST="${{ steps.get_latest.outputs.latest_tag }}"
           if [ "$CURRENT" != "$LATEST" ] || [ "${{ github.event.inputs.force_build }}" = "true" ]; then
             echo "has_new=true" >> $GITHUB_OUTPUT
+            echo "New version released. Let's build new image!"
           else
             echo "has_new=false" >> $GITHUB_OUTPUT
+            echo "New version not found. Nothing to build..."
           fi
+          
+  release:
+    needs: check-version #[check-version, build]
+    if: needs.check-version.outputs.has_new == 'true'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts
+
+      - name: Update version
+        run: |
+          echo "${{ needs.check-version.outputs.latest_tag }}" > $VERSION_FILE
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add $VERSION_FILE
+          git commit -m "New release ${{ needs.check-version.outputs.latest_tag }}" || true
+          git push || true
+          
   build:
     needs: check-version
     if: needs.check-version.outputs.has_new == 'true'
